#version: '3.8'
#services:
#  oracle:
#    image: gvenzl/oracle-xe:latest
#    environment:
#      ORACLE_RANDOM_PASSWORD: true
#      APP_USER: my_user
#      APP_USER_PASSWORD: my_password_which_I_really_should_change
#    ports:
#      - 1521:1521
#
##  db:
##    image: 'postgres:15.3-alpine'
##    container_name: db
##    environment:
##      - POSTGRES_USER=compose-postgres
##      - POSTGRES_PASSWORD=compose-postgres
##  oracle-db:
##    image: doctorkirk/oracle-19c
##    container_name: oracle-db
##    environment:
##      - ORACLE_SID=ORCLCDB
##      - ORACLE_PDB=ORCLPDB1
##      - ORACLE_PWD=doguscan
##      - ORACLE_CHARACTERSET=AL32UTF8
##    ports:
##      - "1521:1521"
##      - "5500:5500"
##    volumes:
##      - oracle-data:/opt/oracle/oradata
##    healthcheck:
##      test: ["CMD-SHELL", "echo 'SELECT 1 FROM DUAL;' | sqlplus -s SYSTEM/doguscan@//localhost:1521/ORCLCDB"]
##      interval: 1m
##      timeout: 30s
##      retries: 5
##      start_period: 40s
#
##  spring-boot-app:
##    image: your-spring-boot-app-image
##    container_name: spring-boot-app
##    ports:
##      - "8080:8080"
##    environment:
##      - SPRING_DATASOURCE_URL=jdbc:oracle:thin:@oracle-db:1521/ORCLCDB
##      - SPRING_DATASOURCE_USERNAME=system
##      - SPRING_DATASOURCE_PASSWORD=yourPassword
##    depends_on:
##      oracle-db:
##        condition: service_healthy
#
##volumes:
##  oracle-data:
##    driver: local
