spring:
  application:
    name: CoinChangeRest

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/student_db
    username: root
    password: doguscan

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

valid:
  bills: 1,2,5,10,20,50,100

coin:
  denominations: 0.25,0.10,0.05,0.01

management:
  endpoints:
    web:
      exposure:
        include: health,info
  info:
    env:
      enabled: true